:original_name: modelarts_13_0073.html

.. _modelarts_13_0073:

Service Code Issues
===================

-  :ref:`Error Message "pandas.errors.ParserError: Error tokenizing data. C error: Expected .* fields" Displayed in Logs <modelarts_trouble_0050>`
-  :ref:`Error Message "max_pool2d_with_indices_out_cuda_frame failed with error code 0" Displayed in Logs <modelarts_trouble_0037>`
-  :ref:`Training Job Failed with Error Code 139 <modelarts_trouble_0039>`
-  :ref:`Debugging Training Code in the Cloud Environment If a Training Job Failed <modelarts_trouble_0057>`
-  :ref:`Error Message "'(slice(0, 13184, None), slice(None, None, None))' is an invalid key" Displayed in Logs <modelarts_trouble_0059>`
-  :ref:`Error Message "DataFrame.dtypes for data must be int, float or bool" Displayed in Logs <modelarts_trouble_0058>`
-  :ref:`Error Message "CUDNN_STATUS_NOT_SUPPORTED." Is Printed in Logs <modelarts_trouble_0056>`
-  :ref:`Error Message "Out of bounds nanosecond timestamp" Displayed in Logs <modelarts_trouble_0053>`
-  :ref:`Error Message "Unexpected keyword argument passed to optimizer" Displayed in Logs <modelarts_trouble_0055>`
-  :ref:`Error Message "no socket interface found" Displayed in Logs <modelarts_trouble_0038>`
-  :ref:`tf.variable Unavailable for Distributed TensorFlow <modelarts_13_0016>`
-  :ref:`Creating a KVStore Using MXNet Blocked and No Error Reported <modelarts_13_0026>`
-  :ref:`Training Job Failed Due to an ECC Error <modelarts_13_0028>`
-  :ref:`Training Job Failed Because the Maximum Recursion Depth Is Exceeded <modelarts_13_0034>`
-  :ref:`Training Using a Built-in Algorithm Failed Due to a bndbox Error <modelarts_13_0041>`
-  :ref:`Training Job in "Reviewing Job Initialization" State <modelarts_13_0030>`
-  :ref:`Training Job Process Exits Unexpectedly <modelarts_13_0074>`
-  :ref:`Stopped Training Job Process <modelarts_13_0075>`

.. toctree::
   :maxdepth: 1
   :hidden: 

   error_message_pandas.errors.parsererror_error_tokenizing_data._c_error_expected_.*_fields_displayed_in_logs
   error_message_max_pool2d_with_indices_out_cuda_frame_failed_with_error_code_0_displayed_in_logs
   training_job_failed_with_error_code_139
   debugging_training_code_in_the_cloud_environment_if_a_training_job_failed
   error_message_slice0_13184_none_slicenone_none_none_is_an_invalid_key_displayed_in_logs
   error_message_dataframe.dtypes_for_data_must_be_int_float_or_bool_displayed_in_logs
   error_message_cudnn_status_not_supported._is_printed_in_logs
   error_message_out_of_bounds_nanosecond_timestamp_displayed_in_logs
   error_message_unexpected_keyword_argument_passed_to_optimizer_displayed_in_logs
   error_message_no_socket_interface_found_displayed_in_logs
   tf.variable_unavailable_for_distributed_tensorflow
   creating_a_kvstore_using_mxnet_blocked_and_no_error_reported
   training_job_failed_due_to_an_ecc_error
   training_job_failed_because_the_maximum_recursion_depth_is_exceeded
   training_using_a_built-in_algorithm_failed_due_to_a_bndbox_error
   training_job_in_reviewing_job_initialization_state
   training_job_process_exits_unexpectedly
   stopped_training_job_process
