:original_name: modelarts_13_0073.html

.. _modelarts_13_0073:

Service Code Issues
===================

-  :ref:`Error Message "pandas.errors.ParserError: Error tokenizing data. C error: Expected .* fields" Displayed in Logs <modelarts_trouble_0050>`
-  :ref:`Error Message "max_pool2d_with_indices_out_cuda_frame failed with error code 0" Displayed in Logs <modelarts_trouble_0037>`
-  :ref:`Debugging Training Code in the Cloud Environment If a Training Job Failed <modelarts_trouble_0057>`
-  :ref:`Error Message "'(slice(0, 13184, None), slice(None, None, None))' is an invalid key" Displayed in Logs <modelarts_trouble_0059>`
-  :ref:`Error Message "DataFrame.dtypes for data must be int, float or bool" Displayed in Logs <modelarts_trouble_0058>`
-  :ref:`Error Message "CUDNN_STATUS_NOT_SUPPORTED" Displayed in Logs <modelarts_trouble_0056>`
-  :ref:`Error Message "Out of bounds nanosecond timestamp" Displayed in Logs <modelarts_trouble_0053>`
-  :ref:`Error Message "Unexpected keyword argument passed to optimizer" Displayed in Logs <modelarts_trouble_0055>`
-  :ref:`Error Message "no socket interface found" Displayed in Logs <modelarts_trouble_0038>`
-  :ref:`Error Message "Runtimeerror: Dataloader worker (pid 46212) is killed by signal: Killed BP" Displayed in Logs <modelarts_trouble_0060>`
-  :ref:`Error Message "AttributeError: 'NoneType' object has no attribute 'dtype'" Displayed in Logs <modelarts_trouble_0063>`
-  :ref:`Error Message "No module name 'unidecode'" Displayed in Logs <modelarts_trouble_0064>`
-  :ref:`Distributed Tensorflow Cannot Use tf.variable <modelarts_13_0016>`
-  :ref:`When MXNet Creates kvstore, the Program Is Blocked and No Error Is Reported <modelarts_13_0026>`
-  :ref:`ECC Error Occurs in the Log, Causing Training Job Failure <modelarts_13_0028>`
-  :ref:`Training Job Failed Because the Maximum Recursion Depth Is Exceeded <modelarts_13_0034>`
-  :ref:`Training Using a Built-in Algorithm Failed Due to a bndbox Error <modelarts_13_0041>`
-  :ref:`Training Job Status Is Reviewing Job Initialization <modelarts_13_0030>`
-  :ref:`Training Job Process Exits Unexpectedly <modelarts_13_0074>`
-  :ref:`Stopped Training Job Process <modelarts_13_0075>`

.. toctree::
   :maxdepth: 1
   :hidden: 

   error_message_pandas.errors.parsererror_error_tokenizing_data._c_error_expected_._fields_displayed_in_logs
   error_message_max_pool2d_with_indices_out_cuda_frame_failed_with_error_code_0_displayed_in_logs
   debugging_training_code_in_the_cloud_environment_if_a_training_job_failed
   error_message_slice0_13184_none_slicenone_none_none_is_an_invalid_key_displayed_in_logs
   error_message_dataframe.dtypes_for_data_must_be_int_float_or_bool_displayed_in_logs
   error_message_cudnn_status_not_supported_displayed_in_logs
   error_message_out_of_bounds_nanosecond_timestamp_displayed_in_logs
   error_message_unexpected_keyword_argument_passed_to_optimizer_displayed_in_logs
   error_message_no_socket_interface_found_displayed_in_logs
   error_message_runtimeerror_dataloader_worker_pid_46212_is_killed_by_signal_killed_bp_displayed_in_logs
   error_message_attributeerror_nonetype_object_has_no_attribute_dtype_displayed_in_logs
   error_message_no_module_name_unidecode_displayed_in_logs
   distributed_tensorflow_cannot_use_tf.variable
   when_mxnet_creates_kvstore_the_program_is_blocked_and_no_error_is_reported
   ecc_error_occurs_in_the_log_causing_training_job_failure
   training_job_failed_because_the_maximum_recursion_depth_is_exceeded
   training_using_a_built-in_algorithm_failed_due_to_a_bndbox_error
   training_job_status_is_reviewing_job_initialization
   training_job_process_exits_unexpectedly
   stopped_training_job_process
